/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package foodlink.forms;

import foodlink.Db;
import foodlink.controllers.Actions;
import foodlink.controllers.Collector;
import foodlink.exceptions.ModelNotFoundException;
import foodlink.exceptions.ValidationException;
import foodlink.models.Category;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author J. Santos
 */
public class CategoryForm extends javax.swing.JFrame {
    
    private Actions currentAction;

    /**
     * Creates new form CategoryForm
     */
    public CategoryForm() {
        initComponents();
        
        this.setCurrentAction(Actions.insert);

        // Popula a tabela de categorias
        List<Category> categories = Db.instance().getCategory().collect(new Collector<Category>());
        DefaultTableModel model = (DefaultTableModel) tblListagem.getModel();
        for (Category cat : categories)
            model.addRow(new Object[] { cat.getName() });
    }

    public Actions getCurrentAction()
    {
        return this.currentAction;
    }

    public void setCurrentAction(Actions value)
    {
        this.currentAction = value;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListagem = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListagemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListagem);

        jLabel1.setText("Nome:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnApagar))
                            .addComponent(jLabel1))
                        .addGap(0, 250, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnApagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.tfNome.setText("");
        this.setCurrentAction(Actions.insert);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        //Apaga itme selecionado na lista
        if (this.tblListagem.getSelectedRow() > -1)
        {
            try
            {
                Db.instance().getCategory().remove(Db.instance().getCategory().get(this.tblListagem.getSelectedRow()));
                ((DefaultTableModel)this.tblListagem.getModel()).removeRow(this.tblListagem.getSelectedRow());
            }
            catch (ModelNotFoundException e)
            {
                System.out.println(e.getMessage());
            }
        }
        else
        {
            System.out.println("Deu néga!");
        }
    }//GEN-LAST:event_btnApagarActionPerformed

    private Category getCategoryFromForm()
    {
         //Retorna uma instância de Category com o Nome que estiver no tfNome
        Category c = new Category();
        c.setName(this.tfNome.getText());
        return c;
    }
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (this.getCurrentAction().equals(Actions.insert))
        {
            try
            {
                //Retorna uma instância de Category com o Nome que estiver no tfNome
                Category cat = this.getCategoryFromForm();
                //Adiciona a nova categoria no "BD
                Db.instance().getCategory().insert(cat);
                ((DefaultTableModel) this.tblListagem.getModel()).addRow(new Object[] { cat.getName() });
                this.tfNome.setText("");
            }
            catch (ValidationException e)
            {
                System.out.println(e.getErrors());
                
            }
        }
        else if (this.getCurrentAction().equals(Actions.update))
        {
            try
            {
                Db.instance().getCategory().update(Db.instance().getCategory().get(this.tblListagem.getSelectedRow()), this.getCategoryFromForm());
                ((DefaultTableModel) this.tblListagem.getModel()).setValueAt(this.tfNome.getText(), this.tblListagem.getSelectedRow(), 0);
            }
            catch (ModelNotFoundException e)
            {
                System.out.println(e.getMessage());
            }
            catch (ValidationException e)
            {
                System.out.println(e.getErrors());
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tblListagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListagemMouseClicked
        if (this.tblListagem.getSelectedRow() > -1)
        {
            this.tfNome.setText(Db.instance().getCategory().get(this.tblListagem.getSelectedRow()).getName());
            this.setCurrentAction(Actions.update);
        }
    }//GEN-LAST:event_tblListagemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoryForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblListagem;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
