package FoodLink.Forms;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import foodlink.Db;
import foodlink.controllers.Actions;
import foodlink.controllers.Collector;
import foodlink.exceptions.ModelNotFoundException;
import foodlink.exceptions.ValidationException;
import java.util.List;
import foodlink.models.Table;
import javax.swing.table.DefaultTableModel;
import foodlink.controllers.Collector;
import foodlink.controllers.TableController;
import foodlink.models.Category;
import javax.swing.JTable;

/**
 *
 * @author Eroneiffson
 */
public class TableForm extends CustomForm<Table, TableController> {
    /**
     * Creates new form TableForm
     */
    public TableForm()
    {}

    @Override
    protected void initialize() {
        initComponents();
    }

    @Override
    protected TableController getController() {
        return Db.instance().getTable();
    }

    @Override
    protected Object[] createRow(Table model) {
        return new Object[] { Integer.toString(model.getCode()) };
    }

    @Override
    protected JTable getTblListagem() {
        return this.tblListagem;
    }

    @Override
    protected void clearForm() {
        this.tfMesa.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbnSalvar = new javax.swing.JButton();
        jbnNovo = new javax.swing.JButton();
        jbnApagar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListagem = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        tfMesa = new javax.swing.JFormattedTextField();

        setTitle("Mesa");

        jLabel1.setText("Mesa:");

        jbnSalvar.setText("Salvar");
        jbnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnSalvarActionPerformed(evt);
            }
        });

        jbnNovo.setText("Novo");
        jbnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnNovoActionPerformed(evt);
            }
        });

        jbnApagar.setText("Apagar");
        jbnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnApagarActionPerformed(evt);
            }
        });

        tblListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mesa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListagem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblListagem.setFocusable(false);
        tblListagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListagemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListagem);

        tfMesa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#####"))));
        tfMesa.setText("efcdtd");
        tfMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfMesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbnSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbnNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbnApagar)))
                        .addGap(0, 169, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnSalvar)
                    .addComponent(tfMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnNovo)
                    .addComponent(jbnApagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnNovoActionPerformed
        this.prepareToNew();
    }//GEN-LAST:event_jbnNovoActionPerformed

    private void jbnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnSalvarActionPerformed
        this.save();
    }//GEN-LAST:event_jbnSalvarActionPerformed

    private void tfMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMesaActionPerformed

    private void tblListagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListagemMouseClicked
        this.tableToForm();
    }//GEN-LAST:event_tblListagemMouseClicked

    private void jbnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnApagarActionPerformed
        this.remove();
    }//GEN-LAST:event_jbnApagarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbnApagar;
    private javax.swing.JButton jbnNovo;
    private javax.swing.JButton jbnSalvar;
    private javax.swing.JTable tblListagem;
    private javax.swing.JFormattedTextField tfMesa;
    // End of variables declaration//GEN-END:variables

    @Override
    protected Table getModelFromForm()
    {
        Table model = new Table();
        model.setCode(Integer.parseInt(this.tfMesa.getText()));
        return model;
    }

    @Override
    protected void modelToForm(Table model)
    {
        this.tfMesa.setText(Integer.toString(model.getCode()));
    }

    

    
}
