package FoodLink.Forms;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import foodlink.Db;
import foodlink.controllers.Actions;
import foodlink.controllers.Collector;
import foodlink.exceptions.ModelNotFoundException;
import foodlink.exceptions.ValidationException;
import java.util.List;
import foodlink.models.Table;
import javax.swing.table.DefaultTableModel;
import foodlink.controllers.Collector;
import foodlink.models.Category;

/**
 *
 * @author Eroneiffson
 */
public class TableForm extends javax.swing.JFrame {
    private Actions currentAction;
    /**
     * Creates new form TableForm
     */
    public TableForm() {
        initComponents();
        this.setCurrentAction(Actions.insert);

        // Popula a tabela de categorias
        List<Table> tables = Db.instance().getTable().collect(new Collector<Table>());
        DefaultTableModel model = (DefaultTableModel) tblListagem.getModel();
        for (Table tab : tables)
            model.addRow(new Object[] { tab.getCode() });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbnSalvar = new javax.swing.JButton();
        jbnNovo = new javax.swing.JButton();
        jbnApagar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListagem = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        tfMesa = new javax.swing.JFormattedTextField();

        setTitle("Mesa");

        jLabel1.setText("Mesa:");

        jbnSalvar.setText("Salvar");
        jbnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnSalvarActionPerformed(evt);
            }
        });

        jbnNovo.setText("Novo");
        jbnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnNovoActionPerformed(evt);
            }
        });

        jbnApagar.setText("Apagar");

        tblListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mesa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListagem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblListagem.setFocusable(false);
        jScrollPane1.setViewportView(tblListagem);

        tfMesa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#####"))));
        tfMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfMesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbnSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbnNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbnApagar)))
                        .addGap(0, 169, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnSalvar)
                    .addComponent(tfMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnNovo)
                    .addComponent(jbnApagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbnNovoActionPerformed

    private void jbnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnSalvarActionPerformed
    if (this.getCurrentAction().equals(Actions.insert))
            {
                try
                {
                    //Retorna uma instância de Category com o Nome que estiver no tfNome
                    Table tab = this.getTableFromForm();
                    //Adiciona a nova categoria no "BD
                    Db.instance().getTable().insert(tab);
                    ((DefaultTableModel) this.tblListagem.getModel()).addRow(new Object[] { tab.getCode() });
                    this.tfMesa.setText("");
                }
                catch (ValidationException e)
                {
                    System.out.println(e.getErrors());

                }
            }
            else if (this.getCurrentAction().equals(Actions.update))
            {
                try
                {
                    Db.instance().getTable().update(Db.instance().getTable().get(this.tblListagem.getSelectedRow()), this.getTableFromForm());
                    ((DefaultTableModel) this.tblListagem.getModel()).setValueAt(this.tfMesa.getText(), this.tblListagem.getSelectedRow(), 0);
                }
                catch (ModelNotFoundException e)
                {
                    System.out.println(e.getMessage());
                }
                catch (ValidationException e)
                {
                    System.out.println(e.getErrors());
                }
            }        // 
    }//GEN-LAST:event_jbnSalvarActionPerformed

    private void tfMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMesaActionPerformed
    public Actions getCurrentAction(){
        return this.currentAction;
    }
    public void setCurrentAction(Actions value)
    {
        this.currentAction = value;
    }
    private Table getTableFromForm()
    {
         //Retorna uma instância de Category com o Nome que estiver no tfNome
        Table t = new Table();
        t.setCode(Integer.parseInt(this.tfMesa.getText()));
        return t;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbnApagar;
    private javax.swing.JButton jbnNovo;
    private javax.swing.JButton jbnSalvar;
    private javax.swing.JTable tblListagem;
    private javax.swing.JFormattedTextField tfMesa;
    // End of variables declaration//GEN-END:variables

    

    
}
